{% set name = "darwin-py" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/darwin-py-{{ version }}.tar.gz
  sha256: 8856e8d52654e7203a05c5ccfe7ef21b40db113013d910736d30d49981f1c83d

build:
  number: 0
  noarch: python
  entry_points:
    - darwin=darwin.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - argcomplete
    - dataclasses
    - humanize
    - numpy
    - pillow
    - python >=3.6
    - pyyaml >=5.1
    - requests
    - tqdm
    - upolygon ==0.1.6

test:
  imports:
    - darwin
    - darwin.dataset
    - darwin.exporter
    - darwin.importer

  commands:
    # disabled because upstream setup.py needs fixing https://github.com/v7labs/darwin-py/issues/144
    # - pip check
    - darwin --help
  requires:
    - pip

about:
  home: https://github.com/v7labs/darwin-py
  summary: Library and command line interface for darwin.v7labs.com
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hajapy
